# Cloudflare Pages configuration
name = "pharmacy-assistant-academy"
compatibility_date = "2024-10-19"
compatibility_flags = ["nodejs_compat"]

# Build configuration
[build]
command = "npm run build"
destination = "dist"

# Environment variables for production
[env.production.vars]
NODE_ENV = "production"
VITE_API_BASE_URL = "https://api.pharmacy-academy.com/api/v1"

# Environment variables for preview
[env.preview.vars]
NODE_ENV = "staging"
VITE_API_BASE_URL = "https://api-staging.pharmacy-academy.com/api/v1"

# Custom domains
[[env.production.routes]]
pattern = "pharmacy-academy.com"
custom_domain = true

[[env.production.routes]]
pattern = "www.pharmacy-academy.com"
custom_domain = true

# Headers and redirects
[site]
bucket = "./dist"

# Functions configuration
[functions]
directory = "./functions"