name = "pharmacy-assistant-academy"
pages_build_output_dir = "dist"
compatibility_date = "2024-10-19"
compatibility_flags = ["nodejs_compat"]

# R2 Bucket binding
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "ttqs"

# Environment variables
[vars]
ENVIRONMENT = "production"
DATABASE_URL = "postgresql://neondb_owner:npg_uBHAc2hinfI4@ep-jolly-frost-a1muxrt0-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
JWT_SECRET = "3939889"