name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'pharmacy-assistant-academy/package-lock.json'
          
      - name: Install dependencies
        working-directory: ./pharmacy-assistant-academy
        run: npm ci
        
      - name: Run tests
        working-directory: ./pharmacy-assistant-academy
        run: npm run test
        
      - name: Build application
        working-directory: ./pharmacy-assistant-academy
        run: npm run build:production
        env:
          NODE_ENV: production
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: pharmacy-assistant-academy
          directory: ./pharmacy-assistant-academy/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Deploy API Worker
        working-directory: ./pharmacy-assistant-academy
        run: npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}